runtime: python39

entrypoint: python main.py

handlers:
- url: /.*
  script: auto

env_variables:
  FLASK_ENV: production
  FLASK_APP: main.py

  FIREBASE_ADMIN_CRED: flask-62adb-firebase-adminsdk-fbsvc-5a7c22f9cc.json
  GOOGLE_APPLICATION_CREDENTIALS: durable-kingdom-456901-u8-db29a531aa4f.json

  ALGOLIA_APP_ID: 2P758DV8OF
  ALGOLIA_API_KEY: f27a5a70218960fb04371982e2ae2a50
  ALGOLIA_INDEX_NAME: jobs

  FIREBASE_WEB_API_KEY: AIzaSyCMgg2THs0owNzhyfb_xmil3dapbmCLRgk

  GOOGLE_SERVICE_ACCOUNT_JSON: flask-62adb-firebase-adminsdk-fbsvc-5a7c22f9cc.json
  GOOGLE_SCOPES: "https://www.googleapis.com/auth/drive.file https://www.googleapis.com/auth/spreadsheets"

  SHEET_KEY: 1jqevTaHVGuDJTnusng_YkcpgOiOzFckt3eYWKO-qF7s
  SHEET1_NAME: Sheet1
  SHEET2_NAME: Sheet2
  SHEET3_NAME: Sheet3

  GDRIVE_FOLDER_ID: 18EbrsLpGepOh5XxYoIIRExdBSjvxaUOR

